services:
    node-a:
        image: nhttpd
        container_name: node-a
        volumes:
            - ./node-a:/usr/local/apache2/htdocs
        environment:
            DISPLAY: 10.0.0.38:0.0
        networks:
            net-1:
                ipv4_address: 10.0.1.3
        cap_add:
            - NET_ADMIN
        command: /usr/local/apache2/htdocs/startup-commands.sh
    node-b:
        image: nhttpd
        container_name: node-b
        volumes:
            - ./node-b:/usr/local/apache2/htdocs
        environment:
            DISPLAY: 10.0.0.38:0.0
        networks:
            net-2:
                ipv4_address: 10.0.2.3
        cap_add:
            - NET_ADMIN
        command: /usr/local/apache2/htdocs/startup-commands.sh
    node-c:
        image: nhttpd
        container_name: node-c
        volumes:
            - ./node-c:/usr/local/apache2/htdocs
        environment:
            DISPLAY: 10.0.0.38:0.0
        networks:
            net-3:
                ipv4_address: 10.0.3.3
        cap_add:
            - NET_ADMIN
        command: /usr/local/apache2/htdocs/startup-commands.sh
    router-1:
        image: nhttpd
        container_name: router-1
        volumes:
            - ./router-1:/usr/local/apache2/htdocs
        environment:
            DISPLAY: 10.0.0.38:0.0
        networks:
            net-1:
                ipv4_address: 10.0.1.2
            net-4:
                ipv4_address: 10.0.4.2
        cap_add:
            - NET_ADMIN
        command: /usr/local/apache2/htdocs/startup-commands.sh
    router-2:
        image: nhttpd
        container_name: router-2
        volumes:
            - ./router-2:/usr/local/apache2/htdocs
        environment:
            DISPLAY: 10.0.0.38:0.0
        networks:
            net-2:
                ipv4_address: 10.0.2.2
            net-4:
                ipv4_address: 10.0.4.3
        cap_add:
            - NET_ADMIN
        command: /usr/local/apache2/htdocs/startup-commands.sh
    router-3:
        image: nhttpd
        container_name: router-3
        volumes:
            - ./router-3:/usr/local/apache2/htdocs
        environment:
            DISPLAY: 10.0.0.38:0.0
        networks:
            net-3:
                ipv4_address: 10.0.3.2
            net-4:
                ipv4_address: 10.0.4.4
        cap_add:
            - NET_ADMIN
        command: /usr/local/apache2/htdocs/startup-commands.sh

networks:
    net-1:
        name: net-1
        ipam:
            driver: default
            config:
                - subnet: 10.0.1.0/24
                  gateway: 10.0.1.1
    net-2:
        name: net-2
        ipam:
            driver: default
            config:
                - subnet: 10.0.2.0/24
                  gateway: 10.0.2.1
    net-3:
        name: net-3
        ipam:
            driver: default
            config:
                - subnet: 10.0.3.0/24
                  gateway: 10.0.3.1
    net-4:
        name: net-4
        ipam:
            driver: default
            config:
                - subnet: 10.0.4.0/24
                  gateway: 10.0.4.1
